
#' Plan for betabinomial fitting
#'
#' This function can tell the plan of betabinomial fitting with some given parameters
#'
#' @param SimP_Dir The directory only contains SimP data generated by function SimP_calculation
#' @param P_cutoff The P-value cutoff. Gene pairs with p-values smaller than the cutoff will be chosen for Betabinomial fitting
#' @param FittingFiles Number of sub-files for the betabinomial fittings
#'
#' @return A list contains the summary and qualified gene pair index
#' @export
#'
#' @examples
#' BBFitting_sup(SimP_Dir = "~/SimP/", P_cutoff = 0.05, FittingFiles= 5)
BBFitting_sup <- function(SimP_Dir, P_cutoff = 0.05, FittingFiles = 5){
  Nfiles <- list.files(SimP_Dir)
  Nfiles <- grep("SimP_",Nfiles)
  Nfiles <- length(Nfiles)

  qualified_idx <- vector("list",Nfiles)
  p <- 0
  for (ii in 1:Nfiles) {
    load(paste0(SimP_Dir,"/SimP_",ii,".RData"))
    qualified_idx[[ii]] <- which(sim.p <= P_cutoff) + p
    p <- p + length(sim.p)
  }

  info_summary <- data.frame(matrix(nrow = FittingFiles, ncol = 2))
  colnames(info_summary) <- c("FittingFile_idx","GenePairs")
  info_summary$FittingFile_idx <- seq(1:nrow(info_summary))

  mean_genepairs <- sum(lengths(qualified_idx)) %/% FittingFiles
  mod_genepairs <- sum(lengths(qualified_idx)) %% FittingFiles

  info_summary$GenePairs <- mean_genepairs
  if (mod_genepairs >= 1) {
    info_summary$GenePairs[1:mod_genepairs] <- info_summary$GenePairs[1:mod_genepairs]+1
  }else{
  }

  IDX <- unlist(qualified_idx)
  info_summary2 <- vector("list",2)
  names(info_summary2) <- c("summary","qualified_gene_idx")
  info_summary2$summary <- info_summary
  info_summary2$qualified_gene_idx <- as.integer(IDX)
  return(info_summary2)

  }
