#' Calculate simulation-based Pvalues
#'
#' This function will calculate the simulation-based P-values based on transformed co-perturbation matrix.
#'
#'
#' @param transformed_CoPM_Dir The directory only contains transformed co-perturbation matrix
#' @param save_path The directory to save the simulation-based P-value
#' @param CoTimes The real co-perturbation times of all gene pairs
#' @param trans_summary result generated by function Transform_CoPM_sup
#' @param Ncores Number of cores to run complete the task
#'
#' @return
#' @export
#'
#' @examples
#' SimPCalculation(transformed_CoPM_Dir = "~/TransformedMatrix/", save_path = "~/SimP/", CoTimes, trans_summary, Ncores = 1)
SimPCalculation <- function(transformed_CoPM_Dir, save_path, CoTimes, trans_summary, Ncores = 1){
  if(dir.exists(save_path)){
  }else{
    stop("Error, save_path not found")
  }

  NTransformedMatrix <- list.files(transformed_CoPM_Dir)
  NTransformedMatrix <- grep("TransformedMatrix_",NTransformedMatrix)
  NTransformedMatrix <- length(NTransformedMatrix)

  NGenePairs <- trans_summary[,2]
  Assignment_table <- data.frame(matrix(nrow = NTransformedMatrix, ncol = 4))
  colnames(Assignment_table) <- c("idx","GenePairs","istart","iend")
  Assignment_table$idx <- seq(1,NTransformedMatrix)
  Assignment_table$GenePairs <- NGenePairs
  Assignment_table$istart[1] <- 1
  Assignment_table$iend[nrow(Assignment_table)] <- sum(Assignment_table$GenePairs)

  if (nrow(Assignment_table) >= 2) {
    for (ii in 1:(nrow(Assignment_table)-1)) {
      Assignment_table$iend[ii] <- Assignment_table$istart[ii] + Assignment_table$GenePairs[ii] - 1
      Assignment_table$istart[ii+1] <- Assignment_table$iend[ii] + 1
    }
  }else{

  }

  coptimes <- vector("list",length = nrow(trans_summary))
  for (ii in 1:nrow(trans_summary)) {
    coptimes[[ii]] <- CoTimes[Assignment_table$istart[ii]:Assignment_table$iend[ii]]
  }

  SimP <- function(idx){
    load(paste0(transformed_CoPM_Dir,"/TransformedMatrix_",idx,".RData"))
    temp <- ifelse(GenePairsVsSims >= coptimes[[idx]], yes = 1, no = 0)
    sim.p <- rowSums(temp)/ncol(temp)
    save(x = sim.p, file = paste0(save_path,"/SimP_",idx,".RData"))
  }

  mc <- getOption("mc.cores", Ncores)
  res <- parallel::mclapply(seq(1:NTransformedMatrix), SimP, mc.cores = mc)

  return(paste0("Done, Please go and check the files in '",save_path,"'"))
}
