#' Transform co-perturbation matrix into gene vs simulation format
#'
#' This function enables transform the gene-gene co-perturbation matrix into gene by simulation format so that p values can be calculated easily when the simulation files are large
#' Please try Transform_CoPM_sup function first with vairable NTransformedMatrix = 1 to see the size of transformed matrix
#' If the size is small enough (depends on the memory of your computer/server), please go with 1 transformed matrix
#' If the size is too large, try different NTransformedMatrix, making sure the size of each file is small.
#'
#' @param RandCoPM_directory The directory contains Random co-perturbation matrix generated by function RandCoPMatrix_Generation
#' @param save_path The directory to save the transformed co-perturbation matrix
#' @param NGenePairs A vector contains Number of gene pairs in each transformed matrix
#' @param NTransformedMatrix Number of Transformed matrix splited in
#' @param Ncores Number of cores to complete the task
#'
#' @return Save the transformed matrix in the given directory
#' @export
#'
#' @examples
#' trans_summary <- Transform_CoPM_sup(RandCoPM_directory = "~/RandBM/", Ngenes = 10, NTransformedMatrix = 1)
#' Transform_CoPM(RandCoPM_directory = "~/RandBM/", save_path = "~/TransformedMatrix/", NGenePairs = trans_summary[,2], NTransformedMatrix = 1, Ncores = 1)
Transform_CoPM <- function(RandCoPM_directory, save_path, NGenePairs, NTransformedMatrix = 1, Ncores = 1){
  if(dir.exists(save_path)){
  }else{
    stop("Error, save_path not found")
  }

  Assignment_table <- data.frame(matrix(nrow = NTransformedMatrix, ncol = 4))
  colnames(Assignment_table) <- c("idx","GenePairs","istart","iend")
  Assignment_table$idx <- seq(1,NTransformedMatrix)
  Assignment_table$GenePairs <- NGenePairs
  Assignment_table$istart[1] <- 1
  Assignment_table$iend[nrow(Assignment_table)] <- sum(Assignment_table$GenePairs)

  if (nrow(Assignment_table) >= 2) {
    for (ii in 1:(nrow(Assignment_table)-1)) {
      Assignment_table$iend[ii] <- Assignment_table$istart[ii] + Assignment_table$GenePairs[ii] - 1
      Assignment_table$istart[ii+1] <- Assignment_table$iend[ii] + 1
    }
  }else{

  }


  GeneVsSims <- function(TransfromedMatrix_idx){
    Nsims <- length(list.files(RandCoPM_directory))
    GenePairsVsSims <- matrix(data = 0, nrow = Assignment_table$GenePairs[TransfromedMatrix_idx], ncol = Nsims)
    for (j in 1:Nsims) {
      load(paste0(RandCoPM_directory,"/CPM_",j,".RData"))
      GenePairsVsSims[,j] <- M2[Assignment_table$istart[TransfromedMatrix_idx]:Assignment_table$iend[TransfromedMatrix_idx]]
      rm(M2)
      gc()
    }
    rownames(GenePairsVsSims) <- seq(Assignment_table$istart[TransfromedMatrix_idx],Assignment_table$iend[TransfromedMatrix_idx])
    save(x = GenePairsVsSims,file = paste0(save_path,"/TransformedMatrix_",TransfromedMatrix_idx,".RData"))
  }

  mc <- getOption("mc.cores", Ncores)
  res <- parallel::mclapply(seq(1:NTransformedMatrix), GeneVsSims, mc.cores = mc)

  return(paste0("Done, Please go and check the files in '",save_path,"'"))
}
